# Uncomment the next line to define a global platform for your project
platform :ios, '9.1'

target 'FieldApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FieldApp
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'JTAppleCalendar', '~> 7.0'
pod 'ImagePicker'
pod "EPSignature"
pod 'Macaw'
pod 'FanMenu'
pod 'SwiftGifOrigin'
# pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream', :branch => 'swift3' ## must be Swift 4+


  target 'FieldAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FieldAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
