# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'FieldApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FieldApp
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'

  target 'FieldAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FieldAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
